---
- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
   - mysql-server

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
